version: "3"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  openapi:
    ports:
      - "8080:8080"
    image: swaggerapi/swagger-ui
    volumes:
      - ${PWD}:/data
    environment:
      SWAGGER_JSON: /data/openapi.yaml
  elasticsearch:
    image: elasticsearch:8.3.2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.3.2
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200